// Responses lead directly to remaining questions; the transcript retains earlier lines.
const pair = (de,en) => ({de,en});
export const dialogueText = (value,language) => typeof value === 'string' ? value : value[language] ?? value.en;
export const ADVENTURE_DIALOGUES = {
    outfitting:{start:'spare',nodes:{
        spare:{text:pair("Ich habe noch ein Langstreckenradar. Es liegt jetzt in deinem Ausrüstungslager. Damit erkennst du Kontakte früher. Bau es vor dem Start ein; dabei lernst du gleich die Schiffsausrüstung kennen.",'I have a spare Long-Baseline Radar. It is in your equipment locker now. It will help you pick up contacts sooner. Fit it before we launch; that will give you a chance to learn your way around the workshop.'),next:'fit'},
        fit:{text:pair("Geh vom MARKTPLATZ zur SCHIFFSAUSRÜSTUNG. Öffne SCHIFFSSYSTEME und tippe auf einen freien Platz für Hilfssysteme. Wähle dort das bereits vorhandene Langstreckenradar. Mit AUS LAGER EINBAUEN bestätigst du den Einbau. Das Teil gehört dir bereits, also kostet es nichts.",'From the market, enter Ship Outfitting. Open SHIP SYSTEMS and tap an empty utility slot. Choose the owned Long-Baseline Radar. Confirm with INSTALL FROM LOCKER. You already own the part, so there is no purchase cost.'),next:'limits'},
        limits:{text:pair("Bei neuen Teilen prüfst du Preis, Größe des Einbauplatzes und Gesamtmasse. Ausgebaute Ausrüstung kommt ins Lager und lässt sich später wieder einbauen oder verkaufen. Deine beiden Strahllaser feuern gemeinsam. Lass ihnen zwischen längeren Feuerstößen Zeit zum Aufladen.",'For new parts, check the price, mount size and total fitting mass. Removed equipment goes into your locker, where you can keep it or sell it. Your two beam lasers fire together. Allow energy to recover between longer bursts.'),choices:[{label:pair("Gut. Ich sehe mir die Schiffsausrüstung an.",'All right. I will find the workshop.'),complete:true}]},
    }},
    navigation:{start:'outside',nodes:{
        outside:{text:pair('Hier ist die Second Light. Ich bin rechts neben dir. Nimm dir einen Moment zum Orientieren. Diesmal setzt du den Kurs selbst.','Second Light here. I am on your right. Take a moment to get your bearings. This time, you will plot the course yourself.'),next:'map'},
        map:{text:pair('Tippe auf das Radar im mittleren Cockpitmonitor. In der Sektorkarte wählst du VESPER an. Die goldene Missionsmarkierung zeigt unser Ziel. Danach schließen wir die Karte und probieren die Flugsteuerung in Ruhe aus.','Tap the radar in the centre cockpit monitor. In the sector chart, select VESPER. The gold mission marker shows our destination. Then we can close the map and try the flight controls at our own pace.'),choices:[{label:pair('Ich setze den Kurs nach Vesper.','I will plot Vesper.'),complete:true}]},
    }},
    services:{start:'check',nodes:{
        check:{text:pair("Die Lieferung ist verkauft. Bevor wir in den Gürtel fliegen, sehen wir unter SERVICE nach dem Schiff. Ein kurzer Blick am Boden erspart uns oft einen langen Rückflug.",'The delivery is sold. Before we head into the belt, let us check the ship at the service desk. A quick look while docked can save us a long flight back.'),next:'resources'},
        resources:{text:pair("Öffne SERVICE in der Dockhalle. Dort füllst du Treibstoff und Raketen nach. Treibstoff braucht nur der Nachbrenner. Der normale Antrieb und der Hyperdrive bringen dich auch mit leerem Tank nach Hause.",'Open SERVICES on the concourse. They refill fuel and missiles. Only the afterburner uses fuel. Normal thrust and hyperdrive can still get you home with an empty tank.'),next:'damage'},
        damage:{text:pair('Schilde erholen sich nach einer kurzen Kampfpause und verbrauchen dabei Energie. Deine Hülle repariert sich nicht von selbst. Lass Schäden hier beheben. Wenn alles voll und heil ist, genügt die Kontrolle; du musst nichts kaufen.','Shields recover after a short break from damage and use energy while recharging. Your hull does not repair itself. Have any damage fixed here. If everything is full and sound, the inspection is enough; there is no need to buy anything.'),choices:[{label:pair("Ich prüfe die Anzeigen unter SERVICE.",'I will check the service desk.'),complete:true}]},
    }},
    weapons:{start:'tools',nodes:{
        tools:{text:pair('Das Erz ist an Bord. Bevor wir weiterfliegen, solltest du wissen, wie du dich verteidigst. Deine beiden Strahllaser sind dafür ein guter Anfang.','The ore is aboard. Before we go further, you should know how to defend yourself. Your two beam lasers are a good place to start.'),next:'groups'},
        groups:{text:pair("Deine Strahllaser treffen sofort und feuern in kurzen Pulsen. Alle Geschütze verbrauchen Energie, die dein Reaktor wieder auflädt. Nur Raketen musst du im Hafen nachkaufen.",'Your beam lasers hit instantly and fire in short pulses. All guns use energy that your reactor restores. Only missiles need restocking at a port.'),next:'energy'},
        energy:{text:pair("Die Energieanzeige steht links zwischen Schilden und Hülle. Lass nach einer Salve den Feuerknopf los, damit der Reaktor nachladen kann. Waffen und Schildaufladung teilen sich diesen Vorrat. Wenn die Energie nicht reicht, zeigt der Waffenmonitor LÄDT an. Deine Flugsteuerung bleibt dabei verfügbar.",'The energy gauge is on the left, between shields and hull. Release the trigger after a burst to let the reactor recharge. Guns and shield recovery share that supply. When energy is low, the weapon monitor shows CHARGING. Your flight controls remain available.'),choices:[{label:pair('Ich achte auf den Energiespeicher.','I will watch the energy reserve.'),complete:true}]},
    }},
    cargo:{start:'clear',nodes:{
        clear:{text:pair('Der Angreifer ist erledigt. Da treibt eine Kiste Erz aus seinem Laderaum. Ich habe sie markiert. Wir können sie mitnehmen, statt sie zwischen den Felsen zurückzulassen.','The attacker is down. There is a crate of ore drifting from his hold. I have marked it. We can take it with us rather than leave it among the rocks.'),next:'scoop'},
        scoop:{text:pair('Flieg langsam an die Kiste heran. Auf kurze Entfernung nimmt das Schiff sie automatisch auf; du brauchst keinen Bergungsstrahl. Im linken Monitor findest du deinen Laderaum. Wenn er voll ist, kannst du dort unerwünschte Handelsware abwerfen.','Approach the crate slowly. At close range, the ship collects it automatically; you do not need the salvage beam. Your hold is in the left monitor. If it is full, you can jettison unwanted trade goods there.'),choices:[{label:pair('Ich hole die Kiste.','I will collect it.'),complete:true}]},
    }},
    galaxy:{start:'route',nodes:{
        route:{text:pair('Das Register liegt in einem anderen Sternsystem. Öffne über das Radar die Karte und wechsle auf GALAXIS. Wähle MERIDIAN. Der Computer setzt das passende Sprungtor als nächsten Wegpunkt.','The ledger is in another star system. Open the map through the radar and switch to GALAXY. Select MERIDIAN. The computer will choose the connecting jump gate as your next waypoint.'),next:'gate'},
        gate:{text:pair('Der Hyperdrive bringt dich innerhalb eines Systems zum Tor. Den eigentlichen Systemwechsel machst du, indem du unter normalem Schub durch die Toröffnung fliegst. Beides kostet keinen Treibstoff.','Hyperdrive takes you to the gate within this system. To change systems, fly through the gate opening under normal thrust. Neither action consumes fuel.'),choices:[{label:pair('Ich plane unsere Route nach Meridian.','I will plot our route to Meridian.'),complete:true}]},
    }},
    mara: {start:'welcome',nodes:{
        welcome:{text:pair('Da bist du ja. Deine Mutter hat zwei Schlüssel für die Wayfarer hinterlassen. Deine Schwester Rin nahm einen. Den anderen habe ich für dich aufgehoben.','There you are. Your mother left two keys to the Wayfarer. Your sister Rin took one. I kept the other for you.'),next:'keys'},
        keys:{text:pair('Hier. Sie hätte sich gefreut, euch beide mit dem Schiff zu sehen.','Here. She would have loved to see you both flying that ship.'),choices:[
            {label:pair('Du hast den Schlüssel die ganze Zeit aufgehoben?','You kept the key all this time?'),next:'kept'},
            {label:pair('Hat Rin wenigstens nach dem anderen gefragt?','Did Rin at least ask for the other one?'),next:'rin'},
            {label:pair('Was muss ich vor dem Start erledigen?','What do I need to do before launching?'),next:'work'},
            {label:pair('Ich spreche mit Rin und besorge die Ware. Bis bald, Mara.','I will talk to Rin and get the cargo. See you soon, Mara.'),complete:true,requires:'work'},
        ]},
        kept:{text:pair('Deine Mutter bat mich darum. Meine Schwester konnte sehr bestimmt sein, wenn ihr etwas am Herzen lag. Ich wollte ihn dir persönlich geben, wenn du bereit bist.','Your mother asked me to. My sister could be very firm about the things that mattered to her. I wanted to give it to you myself, when you were ready.'),next:'memory'},
        memory:{text:pair('Sie wollte, dass ihr beide etwas habt, das euch gehört. Und einen Grund, wieder nach Hause zu kommen. Passt auf das Schiff auf. Und aufeinander.','She wanted you both to have something of your own. And a reason to come home. Look after the ship, and each other.'),returnTo:'keys'},
        rin:{text:pair('Natürlich. Nachdem der Motor lief. In dieser Familie gilt das noch als förmlicher Antrag.','Of course. Once the engine was running. In this family, that still counts as a formal application.'),returnTo:'keys'},
        work:{text:pair("Sprich mit Rin, falls du noch nicht bei ihr warst. Dann kauf an der WARENBÖRSE hier auf Helix zwei Proteinpakete. Auf Vesper könnt ihr sie wieder verkaufen. Für diesen ersten Handel braucht ihr keinen Auftrag von der Auftragstafel.",'Talk to Rin if you have not seen her yet. Then buy two Protein Packs at the commodity market here on Helix. You can sell them on Vesper. You do not need a mission from the board for this first trade.'),next:'food'},
        food:{text:pair('Rin kennt die Strecke und begleitet dich. Kommt danach wieder vorbei und erzählt mir, wie es gelaufen ist.','Rin knows the route and will fly with you. Come back afterwards and tell me how it went.'),returnTo:'keys'},
    }},
    rin:{start:'welcome',nodes:{
        welcome:{text:pair('Die Wayfarer ist startklar. Ich habe die Leitungen geprüft und den Antrieb laufen lassen. Sie hat eine Weile stillgelegen, aber unsere Mutter hat gut auf sie aufgepasst.','The Wayfarer is ready. I checked the lines and ran the drive. She has been idle for a while, but our mother took good care of her.'),next:'hub'},
        hub:{text:pair('Du fliegst die Wayfarer. Ich nehme die Second Light und bleibe bei dir. Wir gehen alles in Ruhe durch.','You fly the Wayfarer. I will take the Second Light and stay with you. We can take this at your pace.'),choices:[
            {label:pair('Wie gut kennst du die Wayfarer?','How well do you know the Wayfarer?'),next:'list'},
            {label:pair('Warum fliegst du nicht mit mir?','Why not fly with me?'),next:'ship'},
            {label:pair('Wie läuft die Lieferung genau?','How does this delivery work?'),next:'delivery'},
            {label:pair('Ich besorge die Ware. Wir sehen uns draußen.','I will get the cargo. See you outside.'),complete:true,requires:'delivery'},
        ]},
        list:{text:pair('Ich bin oft mit unserer Mutter geflogen. Sie konnte am Geräusch erkennen, was dem Schiff fehlte. Meistens war es Treibstoff. Manchmal ihre Geduld.','I flew with our mother often. She could tell what the ship needed just by listening. Usually fuel. Sometimes her patience.'),returnTo:'hub'},
        ship:{text:pair('Von der Second Light aus kann ich deinen Anflug beobachten und dir helfen, wenn du vom Kurs abkommst. Und falls unterwegs etwas passiert, haben wir ein zweites Schiff.','From the Second Light I can watch your approach and help if you drift off course. And if anything happens along the way, we have a second ship.'),next:'promise'},
        promise:{text:pair('Ich bleibe an deinem Flügel. Du musst den ersten Flug nicht allein schaffen.','I will stay on your wing. You do not have to make the first flight alone.'),returnTo:'hub'},
        delivery:{text:pair("Kauf zwei Proteinpakete an der WARENBÖRSE von Helix. Dann fliegen wir nach Vesper, docken an und verkaufen sie dort an der WARENBÖRSE. So lernst du die Strecke kennen und verdienst dir etwas für den nächsten Flug.",'Buy two Protein Packs at Helix’s commodity market. Then we fly to Vesper, dock, and sell them at the market there. You will learn the route and earn something towards the next flight.'),next:'ready'},
        ready:{text:pair('Wenn die Ware an Bord ist, gehen wir noch kurz deine Ausrüstung durch. Danach können wir starten. Ich melde mich über Funk, wenn wir draußen sind.','Once the cargo is aboard, we will check your equipment. Then we can launch. I will call you over the radio when we are outside.'),returnTo:'hub'},
    }},
    mining:{start:'reason',nodes:{
        reason:{text:pair('Das Schiff ist bereit. Jetzt möchte ich dir zeigen, wie du ohne eingekaufte Ware Geld verdienen kannst. Cairn kauft Erz aus dem Shardbelt. Das ist eine Reserve für Treibstoff und Reparaturen, wenn sich ein Handel einmal nicht lohnt.','The ship is ready. Now I want to show you how to earn without buying cargo first. Cairn buys ore from the Shardbelt. That gives you a way to pay for fuel and repairs when a trade is not worth taking.'),next:'route'},
        route:{text:pair('Im Shardbelt üben wir den Abbau an einem Felsen. Dieselbe Zielsteuerung brauchst du bei der Bergung. Danach möchte ich mit dir zur Mourning Line: Dort wurde ein Wrack aus dem Evakuierungskonvoi gefunden, bei dem unsere Mutter flog.','We will practise extraction on a rock in the Shardbelt. Salvage uses the same targeting controls. Then I would like us to visit Mourning Line: a wreck has been found from the evacuation convoy our mother flew with.'),next:'lesson'},
        lesson:{text:pair('Ich markiere eine Lagerstätte, sobald wir im Feld sind. Der Zielmonitor scannt sie automatisch in Reichweite. Geh langsam näher heran, bis ABBAU verfügbar ist, und halte den Knopf gedrückt. Eine Einheit Erz genügt.','I will mark a deposit when we enter the field. The target monitor scans it automatically within range. Approach slowly until MINE is available, then hold the button. One unit of ore is enough.'),choices:[
            {label:pair('Was hat es mit dem Konvoi auf sich?','What was that convoy?'),next:'convoy'},
            {label:pair('Dann fliegen wir zum Shardbelt.','Let us head for the Shardbelt.'),complete:true},
        ]},
        convoy:{text:pair('Unsere Mutter half damals bei der Evakuierung. Einige Schiffe erreichten das Tor nie. In einem der Wracks könnte noch eine Aufzeichnung stecken. Ich möchte wissen, was darauf zu hören ist.','Our mother helped with the evacuation. Some ships never reached the gate. One of the wrecks may still hold a recording. I want to know what is on it.'),returnTo:'lesson'},
    }},
    salvage:{start:'aftermath',nodes:{
        aftermath:{text:pair('Die Kiste ist an Bord. Wenn du Reparaturen brauchst, können wir vorher anlegen. Ansonsten wäre da noch das Wrack, von dem ich dir erzählt habe.','The crate is aboard. We can dock for repairs if you need them. Otherwise, there is still the wreck I told you about.'),next:'request'},
        request:{text:pair("Ich habe den Bergungspunkt als REKORDERSIGNAL DES KONVOIS markiert. Du findest ihn auch außerhalb der Sensorreichweite in der Kontaktliste der NAV-KARTE. Spring zur Mourning Line und folge dann dem Marker. Der rechte Monitor zeigt Scan und Entfernung; in Reichweite hältst du BERGEN gedrückt.",'I have marked the salvage point as CONVOY RECORDER SIGNAL. It stays in the navigation map’s contact list beyond sensor range. Jump to Mourning Line, then follow the marker. The right monitor shows scan and distance; hold SALVAGE once you are within range.'),choices:[
            {label:pair('Du hoffst, dort etwas über unsere Mutter zu finden.','You are hoping to find something about our mother.'),next:'reason'},
            {label:pair('Ich sehe nach, was noch da ist.','I will see what is still there.'),complete:true},
        ]},
        reason:{text:pair('Ja. Ich hätte dir das vor dem Start sagen sollen. Ich wollte erst wissen, ob von dem Wrack überhaupt noch etwas übrig ist.','Yes. I should have told you before we launched. I wanted to know whether there was anything left of the wreck first.'),returnTo:'request'},
    }},
    recorder:{start:'found',nodes:{
        found:{text:pair("Die Aufnahme ist lesbar. Das ist die Stimme unserer Mutter. Der Rekorder stammt aus dem Träger; er hat ihren Funkverkehr mitgeschnitten.",'The recording is readable. That is our mother’s voice. The recorder came from the carrier; it captured her radio transmissions.'),next:'cairn'},
        cairn:{text:pair('Ich war bei diesem Konvoi. Was ich Mara danach erzählt habe, war nicht die ganze Wahrheit. Lass uns bei Cairn Yard anlegen. Ich möchte dir das persönlich erklären.','I was with that convoy. What I told Mara afterwards was not the whole truth. Let us dock at Cairn Yard. I want to explain this in person.'),choices:[
            {label:pair('Gut. Aber diesmal erzählst du mir alles.','All right. But this time, tell me everything.'),complete:true},
        ]},
    }},
    cairn:{start:'account',nodes:{
        account:{text:pair('Meine Maschine fiel kurz vor dem Sprungtor aus. Unsere Mutter verließ mit der Wayfarer die Formation und holte mich an Bord. Der Träger hinter uns schaffte es nicht durch das Tor.','My ship failed just short of the jump gate. Our mother broke formation in the Wayfarer and took me aboard. The carrier behind us never made it through the gate.'),next:'record'},
        record:{text:pair('Im offiziellen Bericht steht, sie sei ohne Freigabe abgedreht. Aber hör hier: Die Konvoileitung bestätigt ihren Rettungsanflug. Genau dieser Funkspruch fehlt im Bericht.','The official report says she turned away without clearance. But listen here: convoy control acknowledges her rescue approach. That transmission is missing from the report.'),next:'confession'},
        confession:{text:pair('Ich habe Mara nie erzählt, dass sie wegen mir abgedreht ist. Ich hatte Angst, sie würde mir die Schuld am Verlust des Trägers geben. Das war unfair gegenüber ihr. Und gegenüber dir.','I never told Mara that she turned back for me. I was afraid she would blame me for the loss of the carrier. That was unfair to her, and to you.'),choices:[
            {label:pair('Beweist die Aufnahme, wer für den Verlust verantwortlich war?','Does the recording prove who was responsible for the loss?'),next:'proof'},
            {label:pair('Warum hast du mir nicht vorher davon erzählt?','Why did you not tell me before?'),next:'silence'},
            {label:pair('Was können wir jetzt tun?','What can we do now?'),next:'plan'},
            {label:pair('Mara muss das erfahren. Schick ihr eine Kopie.','Mara needs to hear this. Send her a copy.'),next:'tell',requires:'plan'},
            {label:pair('Ich vertraue dir. Wir suchen gemeinsam weiter.','I trust you. We will keep looking together.'),next:'trust',requires:'plan'},
            {label:pair("Ich behalte den Rekorder. Ich brauche Zeit, das einzuordnen.",'I am keeping the recorder. I need time to make sense of this.'),next:'keep',requires:'plan'},
        ]},
        proof:{text:pair('Nein. Sie zeigt, dass der Bericht etwas Wesentliches auslässt. Warum der Träger zurückblieb, wissen wir noch nicht. Dafür brauchen wir das vollständige Evakuierungsregister.','No. It shows that the report leaves out something important. We still do not know why the carrier was left behind. For that, we need the full evacuation ledger.'),returnTo:'confession'},
        silence:{text:pair('Solange ich schwieg, musste ich eure Fragen nicht beantworten. Ich habe mir eingeredet, ich würde euch damit schützen. In Wahrheit habe ich mich selbst geschützt.','As long as I stayed quiet, I did not have to answer your questions. I told myself I was protecting you. Really, I was protecting myself.'),returnTo:'confession'},
        plan:{text:pair('Die Register wurden nach Meridian Prime gebracht. Dort könnte das Original noch liegen. Wir können durch das Helios–Meridian-Tor fliegen. Was Mara von dieser Aufnahme erfährt, entscheiden wir vorher.','The ledgers were moved to Meridian Prime. The original may still be there. We can fly through the Helios–Meridian gate. Before we leave, we should decide what to tell Mara about this recording.'),returnTo:'confession'},
        tell:{text:pair('Ich schicke ihr die Aufnahme und meine Erklärung. Sie soll es von mir erfahren. Danke, dass du mich nicht wieder damit davonkommen lässt.','I will send her the recording and my explanation. She should hear it from me. Thank you for not letting me avoid this again.'),choices:[
            {label:pair('Schick sie ab. Dann brechen wir auf.','Send it. Then we can leave.'),complete:true,tutorialChoice:'tell-mara'},
        ]},
        trust:{text:pair("Danke. Ich werde dir sagen, was ich weiß, auch wenn es unangenehm wird. Den Rekorder bewahren wir auf; wir brauchen ihn vielleicht noch.",'Thank you. I will tell you what I know, even when it is uncomfortable. We will keep the recorder safe; we may still need it.'),choices:[
            {label:pair('Gut. Dann sehen wir gemeinsam weiter.','All right. We will take the next step together.'),complete:true,tutorialChoice:'trust-rin'},
        ]},
        keep:{text:pair('Das verstehe ich. Du hast die Aufnahme geborgen, und du entscheidest, wem du sie zeigst. Ich begleite dich nach Meridian, wenn du das möchtest.','I understand. You recovered the recording, and you decide who sees it. I will fly with you to Meridian if you want me there.'),choices:[
            {label:pair('Komm mit. Das hier ist noch nicht geklärt.','Come with me. We have not settled this yet.'),complete:true,tutorialChoice:'keep-recorder'},
        ]},
    }},
    gate:{start:'crossing',nodes:{
        crossing:{text:pair('Der Kurs zum Helios–Meridian-Tor ist gesetzt. Mit dem Hyperdrive kommst du bis zum Sprungpunkt. Danach übernimmst du wieder: Richte die Wayfarer auf die Öffnung aus und flieg hindurch.','The course to the Helios–Meridian gate is set. Hyperdrive takes you to the jump point. Then take over: line the Wayfarer up with the opening and fly through.'),next:'ready'},
        ready:{text:pair("Auf der anderen Seite beginnt Meridian. Ab dort können uns auf den Handelsrouten auch Piraten begegnen. Behalte das Radar im Blick und lass dir eine freie Route zum nächsten Hafen.",'Meridian is on the other side. Ordinary trade routes will not be sheltered like our practice flight. Watch the radar and keep a clear route to the next port.'),choices:[
            {label:pair('Wir sehen uns auf der anderen Seite.','See you on the other side.'),complete:true},
        ]},
    }},
    ending:{start:'arrived',nodes:{
        arrived:{text:pair('Wir sind durch. Du hast die Wayfarer nach Meridian gebracht. Ich habe dir deinen Anteil überwiesen. Damit hast du eine Reserve für Reparaturen und den nächsten Handel.','We are through. You brought the Wayfarer to Meridian. I have transferred your share. That gives you a reserve for repairs and your next trade.'),next:'lead'},
        lead:{text:pair('Die Aufnahme wirft Fragen auf, die wir noch nicht beantworten können. Ich werde der Spur zum Register nachgehen. Such dir inzwischen Arbeit an den Häfen oder erkunde die Handelsrouten. Du bestimmst deinen nächsten Kurs.','The recording raises questions we cannot answer yet. I will follow up the lead on the ledger. In the meantime, you can find work at the ports or explore the trade routes. You choose your next course.'),next:'work'},
        work:{text:pair('In Hafenbars findest du Aufträge. Prüfe Ziel, Frist, Belohnung und Kaution vor der Annahme. Lieferaufträge brauchen freien Laderaum; ihr versiegelter Inhalt lässt sich nicht normal verkaufen. Dein Schiffsmonitor hält den Fortschritt fest und zeigt, wohin du als Nächstes musst.','Port bars post contracts. Check the destination, deadline, reward and bond before accepting. Deliveries need free cargo space; their sealed contents cannot be sold as ordinary goods. Your ship monitor records progress and shows where you need to go next.'),choices:[
            {label:pair('Wozu sind die Gilden da?','What are the guilds for?'),next:'guilds'},
            {label:pair('Und wenn ich Rennen fliegen möchte?','What if I want to race?'),next:'races'},
            {label:pair('Wie komme ich später an ein anderes Schiff?','How do I get a different ship later?'),next:'ships'},
            {label:pair('Was mache ich, wenn ein Gegner aufgibt?','What do I do if an opponent surrenders?'),next:'surrender'},
            {label:pair('Was sollte ich vor dem nächsten Flug noch wissen?','What else should I know before my next flight?'),next:'saves'},
            {label:pair('Melde dich, wenn du etwas erfährst. Pass auf dich auf, Rin.','Call me if you learn anything. Take care, Rin.'),complete:true},
        ]},
        guilds:{text:pair("Sprich mit den Gildenvertretern in den Bars. Dein Ansehen bei ihnen zählt: Erledigte Aufträge und passende Arbeit verbessern deinen Rang und öffnen bessere Angebote und Ausrüstung. Für manche Teile reicht Geld allein nicht aus.",'Speak to guild representatives in the bars. Reputation matters: completed contracts and relevant work improve your rank and unlock better offers and equipment. Some parts need more than money.'),returnTo:'work'},
        races:{text:pair("Im RENNBÜRO meldest du dich für eine Rennstrecke an. Nach der Anmeldung zeigt die Karte zuerst den Sammelpunkt. Flieg dorthin, warte den Countdown ab und passiere die Tore der Reihe nach. Achte auf Gebühren und Fristen; ein verpasstes Tor zählt nicht als Abkürzung.",'Race desks take course entries. After you enter, the map first shows the gathering point. Fly there, wait for the countdown, then pass through the gates in order. Check entry fees and deadlines; missing a gate does not count as a shortcut.'),returnTo:'work'},
        ships:{text:pair("Auf dem MARKTPLATZ größerer Häfen findest du die WERFT. Vergleiche Laderaum, Halterungen und Flugeigenschaften. Dein altes Schiff wird beim Kauf angerechnet. Eigene Ausrüstung wandert ins Lager; prüfe danach die neue Bestückung und fülle Raketen nach.",'Larger ports have shipyards in their markets. Compare cargo space, mounts and flight characteristics. Your old ship is credited against the purchase. Your own equipment moves to the locker; check the new fitting and restock missiles afterwards.'),returnTo:'work'},
        surrender:{text:pair('Hör auf zu feuern. Bei einem gesuchten Piloten wechselt die blaue Taste zur Übernahme des Schiffes, sobald die Übergabe möglich ist. Nähere dich und bestätige sie, statt das Schiff zu zerstören. Manche Piraten verlangen auch Geld oder Ware; du kannst ihre Forderung bezahlen, wenn dir das sicherer erscheint.','Stop firing. For a wanted pilot, the blue button changes from firing missiles to capturing the ship when a handover is available. Approach and confirm it instead of destroying the ship. Some pirates demand money or cargo; you can meet their demand if that seems safer.'),returnTo:'work'},
        saves:{text:pair('Die Taste oben links pausiert den Flug. Dort findest du Einstellungen und Speichern. Die Karriere wird außerdem automatisch in diesem Browser gesichert. Schau vor einem längeren Flug nach Hülle, Raketen und Laderaum. Und komm gelegentlich bei Mara vorbei.','The button at the upper left pauses flight. Settings and Save are there. Your career also saves automatically in this browser. Before a long trip, check hull, missiles and cargo space. And visit Mara now and then.'),returnTo:'work'},
    }},
    combat:{start:'contact',nodes:{
        contact:{text:pair('Ein einzelner Plünderer: Ash Moth. Ich habe ihn für dich als Ziel markiert. Bevor wir ihn angehen, erkläre ich dir die Waffensteuerung.','One raider: Ash Moth. I have marked him as your target. Before we engage, let me explain the weapon controls.'),next:'guns'},
        guns:{text:pair('Deine Strahllaser feuern kurze Pulse und helfen beim Zielen. Sie verbrauchen Energie, die dein Reaktor wieder auflädt. Richte das Fadenkreuz auf sein Schiff und halte den roten Feuerknopf gedrückt. Achte links auf deine Energie und rechts auf seine Schilde und Hülle. Lass den Feuerknopf zwischen Salven los. Liegt ein Felsen dazwischen, such dir eine freie Schussbahn.','Your beam lasers fire short pulses and help with aiming. They use energy that your reactor restores. Keep your crosshair on his ship and hold the red fire button. Watch your energy on the left and his shields and hull on the right. Release the trigger between bursts. If a rock gets in the way, find a clear line of fire.'),next:'missiles'},
        missiles:{text:pair("Die blaue Taste feuert eine Rakete auf das angewählte Schiff. Ohne Schiffsziel startet sie nicht. Neben der Taste siehst du den Munitionsvorrat; bei mehreren Werfern wechselst du dort den Werfer. Neue Raketen bekommst du unter SERVICE eines Hafens.",'The blue button fires a missile at the selected ship. It will not launch without a ship target. The readout beside it shows your remaining rounds; with several launchers fitted, tap it to change launcher. Ports restock missiles at the service desk.'),next:'help'},
        help:{text:pair('Deine Bordwaffen reichen für diesen Gegner. Du kannst auch Raketen einsetzen, wenn du freie Sicht hast. Bleib in Bewegung. Wenn es eng wird, greife ich ein.','Your guns are enough for this opponent. You can also use missiles when you have a clear shot. Keep moving. If things get rough, I will step in.'),choices:[
            {label:pair('Ich bin bereit. Bleib in meiner Nähe.','I am ready. Stay close.'),complete:true},
        ]},
    }},
    flight:{start:'hello',nodes:{
        hello:{text:pair('Der Kurs steht. Bevor wir den Hyperdrive einschalten, probieren wir die Steuerung hier draußen aus. Ich bleibe bei dir.','The course is set. Before we engage hyperdrive, let us try the controls here in open space. I will stay with you.'),next:'hub'},
        hub:{text:pair('Mit dem Schieber links regelst du den Schub. Steuere mit dem Joystick oder durch Neigen, falls das aktiviert ist. Dann probierst du einen kurzen Nachbrennerstoß mit der goldenen Taste. Über Funk gehen wir danach die beiden äußeren Monitore durch.','The slider on the left controls thrust. Steer with the joystick, or tilt your phone if that is enabled. Then try a short afterburner burst with the gold button. Over the radio, we will go through the two outer monitors afterwards.'),choices:[
            {label:pair('Wie finde ich Vesper?','How do I find Vesper?'),next:'route'},
            {label:pair('Ich bin noch ziemlich unsicher.','I am still feeling rather unsure.'),next:'reassure'},
            {label:pair('Alles klar. Bleib an meinem Flügel.','All right. Stay on my wing.'),complete:true},
        ]},
        route:{text:pair("Vesper ist bereits angewählt. Der Hyperdrive bringt dich in die Nähe der Kolonie. Lass Vesper danach angewählt und nähere dich langsam; die Landung erfolgt automatisch. Über den mittleren Monitor öffnest du die NAV-KARTE.",'Vesper is already selected. Hyperdrive takes you close to the colony. Keep Vesper selected afterwards and approach slowly; landing is automatic. You can check the navigation map through the centre monitor.'),returnTo:'hub'},
        reassure:{text:pair('Das ging mir beim ersten Flug genauso. Nimm den Schub zurück, wenn du Zeit zum Orientieren brauchst. Wir haben es nicht eilig, und ich bin direkt neben dir.','I felt the same on my first flight. Ease off the throttle if you need time to get your bearings. We are in no hurry, and I am right beside you.'),returnTo:'hub'},
    }},
};
