// New-system content kept separate from the legacy location table while the
// galaxy model is rolled out.  The catalog is deliberately data-only: callers
// can merge or filter it without having to import any game systems.

export const GALAXY_LOCATIONS = {
    cairn: {
        id: 'cairn',
        systemId: 'helios-verge',
        name: 'Cairn Yard',
        shortName: 'CAIRN',
        kind: 'station',
        position: [-158000, 22000, 146000],
        radius: 520,
        dockRadius: 980,
        faction: 'salvage-union',
        accent: '#c98a52',
        secondary: '#3d2e2b',
        description: 'A small fuel and repair depot beside the Mourning Line, and the home of Helios Verge’s informal racing scene.',
        services: {
            fuel: true,
            repair: true,
            market: false,
            bar: true,
            shipyard: false,
            outfitting: false,
            missions: false,
            race: true,
        },
        encounterRate: 0.48,
        people: [
            {
                id: 'juno-rell',
                name: 'Juno Rell',
                role: 'Race coordinator',
                affiliation: 'Cairn Yard Racing League',
                portraitSeed: 214,
                lines: [
                    'The course starts in the wrecks and ends wherever the last pilot crawls back to the dock.',
                    'If you can see the next gate clearly, you are probably taking the safe line.',
                    'Cairn has cheap fuel, quick patches, and no patience for excuses after the flag drops.',
                ],
            },
            {
                id: 'merrit-voss',
                name: 'Merrit Voss',
                role: 'Depot mechanic',
                affiliation: 'Salvage Union',
                portraitSeed: 227,
                lines: [
                    'Bring me a ship with a pulse and I can usually send it back out. Usually.',
                    'The wrecks do not care how fast you are. They only care whether you turn in time.',
                    'Do not burn your reserve on the way here. A damaged engine is easier to fix than an empty tank.',
                ],
            },
        ],
    },

    'meridian-prime': {
        id: 'meridian-prime',
        systemId: 'meridian',
        name: 'Meridian Prime',
        shortName: 'MERIDIAN',
        kind: 'planet',
        position: [198000, -32000, -174000],
        radius: 18400,
        dockRadius: 23800,
        faction: 'concord',
        accent: '#7ebbd8',
        secondary: '#233a53',
        description: 'A crowded core world wrapped in orbital infrastructure, consuming raw materials and exporting manufactured goods.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 1.08,
            food: 1.04,
            medicine: 0.88,
            electronics: 0.76,
            machinery: 0.84,
            ore: 0.72,
            gold: 0.92,
            scrap: 0.82,
            luxuries: 0.94,
            arms: 1.22,
        },
        marketBias: {
            water: 8,
            food: 10,
            medicine: -12,
            electronics: -20,
            machinery: -18,
            ore: 25,
            gold: 4,
            scrap: 18,
            luxuries: -6,
            arms: 16,
        },
        shipsForSale: ['talon', 'atlas', 'lancer'],
        encounterRate: 0.22,
        people: [
            {
                id: 'leon-vale',
                name: 'Leon Vale',
                role: 'Orbital market factor',
                marketTipster: true,
                affiliation: 'Merchant Guild',
                portraitSeed: 241,
                lines: [
                    'Meridian does not lack cargo. It lacks cargo that arrived before somebody needed it.',
                    'Ore and scrap sell cleanly here; advanced electronics leave the docks before the invoices cool.',
                    'If a quote looks generous, check the customs fee before you celebrate.',
                ],
            },
            {
                id: 'sela-orrin',
                name: 'Sela Orrin',
                role: 'Concord customs liaison',
                affiliation: 'Concord Patrol',
                portraitSeed: 253,
                lines: [
                    'A complete manifest makes a short inspection. A clever manifest makes a long day.',
                    'Keep your transponder live inside the approach lanes and nobody needs to raise their voice.',
                    'The city buys almost anything, but it records who brought it through the gate.',
                ],
            },
            {
                id: 'tomas-quin',
                name: 'Tomas Quin',
                role: 'Dockside courier',
                affiliation: 'Free Merchants Compact',
                portraitSeed: 266,
                lines: [
                    'Meridian traffic looks slow until you are the one trying to cross it.',
                    'The best contracts pay for a clean arrival, not a dramatic departure.',
                    'Argent builds the beautiful ships. Meridian finds ways to fill their holds.',
                ],
            },
        ],
    },

    argent: {
        id: 'argent',
        systemId: 'meridian',
        name: 'Argent Shipworks',
        shortName: 'ARGENT',
        kind: 'station',
        position: [-122000, 30000, 144000],
        radius: 1420,
        dockRadius: 2080,
        faction: 'concord',
        accent: '#a7c8d2',
        secondary: '#30424d',
        description: 'A vast orbital construction complex where civilian and military hulls are assembled, repaired, and refitted.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 1.02,
            food: 1.02,
            medicine: 0.96,
            electronics: 0.72,
            machinery: 0.68,
            ore: 0.78,
            gold: 0.88,
            scrap: 0.65,
            luxuries: 1.12,
            arms: 0.9,
        },
        marketBias: {
            water: 2,
            food: 3,
            medicine: -4,
            electronics: -26,
            machinery: -30,
            ore: 20,
            gold: 5,
            scrap: 28,
            luxuries: -10,
            arms: 10,
        },
        shipsForSale: ['vanguard', 'lancer', 'atlas'],
        encounterRate: 0.26,
        people: [
            {
                id: 'arden-kai',
                name: 'Arden Kai',
                role: 'Shipwright foreman',
                affiliation: 'Argent Shipworks',
                portraitSeed: 279,
                lines: [
                    'A ship is not finished when it leaves the frame. It is finished when its pilot trusts every warning light.',
                    'We can build for speed, armor, or cargo. Anyone promising all three is selling a brochure.',
                    'Bring a clean title and a patient wallet. The queue is long because the work is real.',
                ],
            },
            {
                id: 'mira-kest',
                name: 'Mira Kest',
                role: 'Outfitting broker',
                marketTipster: true,
                affiliation: 'Merchant Guild',
                portraitSeed: 291,
                lines: [
                    'The right module saves more credits than the cheapest hull. Fit the job you actually fly.',
                    'Argent buys scrap by the trainload, then sells it back as something you can trust with your life.',
                    'Meridian Prime pays for finished machinery. Frontier yards pay for parts they can repair themselves.',
                ],
            },
            {
                id: 'bram-tel',
                name: 'Bram Tel',
                role: 'Test-flight pilot',
                affiliation: 'Concord Patrol',
                portraitSeed: 304,
                lines: [
                    'Never sign off a drive core while the warning tone is still changing pitch.',
                    'The Foundry Lanes are crowded, but they teach a new hull what a real approach feels like.',
                    'A ship that turns beautifully empty may handle very differently with a full hold.',
                ],
            },
        ],
    },

    'gatehouse-twelve': {
        id: 'gatehouse-twelve',
        systemId: 'meridian',
        name: 'Gatehouse Twelve',
        shortName: 'GATEHOUSE',
        kind: 'station',
        position: [-198000, 16000, 188000],
        radius: 760,
        dockRadius: 1250,
        faction: 'concord',
        accent: '#729eb8',
        secondary: '#293b4a',
        description: 'A compact Concord checkpoint on one of Meridian’s primary jump approaches.',
        services: {
            fuel: true,
            repair: true,
            market: false,
            bar: false,
            shipyard: false,
            outfitting: false,
            missions: true,
            race: false,
        },
        encounterRate: 0.18,
    },

    'foundry-lanes': {
        id: 'foundry-lanes',
        systemId: 'meridian',
        name: 'The Foundry Lanes',
        shortName: 'FOUNDRY',
        kind: 'field',
        position: [-94000, 18000, 137000],
        radius: 3200,
        faction: 'concord',
        accent: '#8daeb5',
        secondary: '#303c46',
        description: 'The crowded industrial space around Argent, where freighters, construction craft, and patrols cross constantly.',
        encounterRate: 0.42,
    },

    blackglass: {
        id: 'blackglass',
        systemId: 'redwake',
        name: 'Blackglass',
        shortName: 'BLACKGLASS',
        kind: 'station',
        position: [-178000, -26000, 142000],
        radius: 5480,
        dockRadius: 7920,
        faction: 'red-talons',
        accent: '#d26759',
        secondary: '#4c2025',
        description: 'A sprawling freeport cut into a dark moon, held together by uneasy bargains between crews, merchants, and syndicates.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 1.62,
            food: 1.48,
            medicine: 1.58,
            electronics: 1.08,
            machinery: 1.25,
            ore: 0.95,
            gold: 0.76,
            scrap: 0.72,
            luxuries: 0.86,
            arms: 0.74,
        },
        marketBias: {
            water: -30,
            food: -26,
            medicine: -28,
            electronics: 4,
            machinery: -8,
            ore: 14,
            gold: 12,
            scrap: 24,
            luxuries: 16,
            arms: 48,
        },
        shipsForSale: ['talon', 'vanguard', 'prospector'],
        encounterRate: 0.62,
        people: [
            {
                id: 'vesh-orr',
                name: 'Vesh Orr',
                role: 'Freeport fixer',
                marketTipster: true,
                affiliation: 'Red Talon Syndicate',
                portraitSeed: 318,
                lines: [
                    'Blackglass has no law worth memorizing. It has agreements, and agreements have witnesses.',
                    'Food and medigel are expensive because somebody has to bring them through the dark.',
                    'If a crate has no clean story, it usually has a better price.',
                ],
            },
            {
                id: 'nara-quill',
                name: 'Nara Quill',
                role: 'Independent broker',
                marketTipster: true,
                affiliation: 'Free Merchants Compact',
                portraitSeed: 331,
                lines: [
                    'Never ask who owns a dock here. Ask who can close it before you finish the sentence.',
                    'Cinder pays for honest freight. Blackglass pays for freight that arrived unnoticed.',
                    'A good price in Redwake is one that still looks good after you count the escort.',
                ],
            },
            {
                id: 'kellan-rusk',
                name: 'Kellan Rusk',
                role: 'Mercenary captain',
                affiliation: 'Independent',
                portraitSeed: 344,
                lines: [
                    'The belt is cover, not safety. Anyone who tells you otherwise is trying to sell you a route.',
                    'If you take a contract from the Talons, read the last line twice. That is where the real job starts.',
                    'A full hold paints a target on your transponder, even when the transponder is off.',
                ],
            },
        ],
    },

    cinder: {
        id: 'cinder',
        systemId: 'redwake',
        name: 'Cinder Station',
        shortName: 'CINDER',
        kind: 'station',
        position: [188000, 14000, -160000],
        radius: 1260,
        dockRadius: 1860,
        faction: 'free-merchants',
        accent: '#c48a62',
        secondary: '#473338',
        description: 'An aging independent industrial station kept alive by refining, freight work, and stubborn local crews.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 1.38,
            food: 1.25,
            medicine: 1.3,
            electronics: 1.18,
            machinery: 0.8,
            ore: 0.64,
            gold: 0.86,
            scrap: 0.7,
            luxuries: 1.42,
            arms: 1.02,
        },
        marketBias: {
            water: -18,
            food: -12,
            medicine: -16,
            electronics: 10,
            machinery: -22,
            ore: 36,
            gold: 7,
            scrap: 30,
            luxuries: -20,
            arms: 18,
        },
        shipsForSale: ['prospector', 'atlas'],
        encounterRate: 0.5,
        people: [
            {
                id: 'mara-jen',
                name: 'Mara Jen',
                role: 'Station quartermaster',
                marketTipster: true,
                affiliation: 'Free Merchants Compact',
                portraitSeed: 357,
                lines: [
                    'Cinder survives because every broken machine becomes somebody else’s spare part.',
                    'Machinery is cheap when the refinery is working. When it is not, every bolt becomes a luxury.',
                    'Blackglass pays more for necessities, but it also asks more questions about who delivered them.',
                ],
            },
            {
                id: 'dax-hollis',
                name: 'Dax Hollis',
                role: 'Refinery engineer',
                affiliation: 'Cinder Independent Assembly',
                portraitSeed: 369,
                lines: [
                    'The station sounds rough because it is still running. Quiet machinery is usually dead machinery.',
                    'Bring clean water and replacement pumps. Bring anything else only if you have room.',
                    'Torchwell has fuel. Cinder has the people who can explain why your engine drank it all.',
                ],
            },
            {
                id: 'rhea-sol',
                name: 'Rhea Sol',
                role: 'Freight dispatcher',
                affiliation: 'Merchant Guild',
                portraitSeed: 382,
                lines: [
                    'A safe route in Redwake is one where the other pilot has somewhere better to be.',
                    'Keep your delivery times realistic. The belt does not care what the contract promised.',
                    'Cinder will not ask what you are carrying if the seals and the payment both check out.',
                ],
            },
        ],
    },

    torchwell: {
        id: 'torchwell',
        systemId: 'redwake',
        name: 'Torchwell',
        shortName: 'TORCHWELL',
        kind: 'station',
        position: [-48000, -18000, 212000],
        radius: 820,
        dockRadius: 1320,
        faction: 'free-merchants',
        accent: '#d18c55',
        secondary: '#492b2b',
        description: 'A lonely outer-route refinery offering fuel, basic repairs, and little else.',
        services: {
            fuel: true,
            repair: true,
            market: false,
            bar: false,
            shipyard: false,
            outfitting: false,
            missions: true,
            race: false,
        },
        encounterRate: 0.56,
    },

    'redwake-belt': {
        id: 'redwake-belt',
        systemId: 'redwake',
        name: 'The Redwake Belt',
        shortName: 'REDWAKE',
        kind: 'field',
        position: [118000, 18000, -62000],
        radius: 3420,
        faction: 'red-talons',
        accent: '#9a6c61',
        secondary: '#39252b',
        description: 'A broken asteroid region where raiders, bounty targets, and patient pilots use the rocks to disappear.',
        encounterRate: 0.78,
    },

    nacre: {
        id: 'nacre',
        systemId: 'pale-ring',
        name: 'Nacre Station',
        shortName: 'NACRE',
        kind: 'station',
        position: [208000, 26000, -176000],
        radius: 1320,
        dockRadius: 1950,
        faction: 'concord',
        accent: '#c4d9dc',
        secondary: '#3b5965',
        description: 'A scientific habitat supporting planetary research, medical laboratories, and long-range survey work.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 0.7,
            food: 1.2,
            medicine: 0.72,
            electronics: 0.78,
            machinery: 1.42,
            ore: 1.16,
            gold: 0.9,
            scrap: 1.34,
            luxuries: 1.48,
            arms: 1.26,
        },
        marketBias: {
            water: 24,
            food: -14,
            medicine: 28,
            electronics: 24,
            machinery: -26,
            ore: -8,
            gold: 4,
            scrap: -16,
            luxuries: -25,
            arms: 8,
        },
        shipsForSale: ['talon', 'prospector'],
        encounterRate: 0.34,
        people: [
            {
                id: 'dr-elin-saye',
                name: 'Dr. Elin Saye',
                role: 'Research director',
                marketTipster: true,
                affiliation: 'Pale Ring Survey Authority',
                portraitSeed: 395,
                lines: [
                    'The rings are not empty. They are merely very good at hiding the evidence.',
                    'Bring intact probes and clean sensor logs. We can learn more from a boring return than a heroic story.',
                    'Medical compounds hold their value here because resupply takes longer than most illnesses.',
                ],
            },
            {
                id: 'pavel-orn',
                name: 'Pavel Orn',
                role: 'Survey dispatcher',
                affiliation: 'Pale Ring Survey Authority',
                portraitSeed: 408,
                lines: [
                    'A clear route through the rings is temporary. Record it, then assume it has moved.',
                    'Shepherd Relay is small, but every survey crew checks in there before entering the dense bands.',
                    'If your instruments disagree, trust the one that still remembers when it last had a signal.',
                ],
            },
            {
                id: 'tessa-rye',
                name: 'Tessa Rye',
                role: 'Clinic quartermaster',
                affiliation: 'Civilian Medical Service',
                portraitSeed: 421,
                lines: [
                    'A damaged probe is an expense. A damaged medical shipment is a problem with names attached.',
                    'Nacre has laboratories. Boreal has water. Neither has enough spare machinery.',
                    'The best explorers are the ones who come back with both the data and the ship.',
                ],
            },
        ],
    },

    boreal: {
        id: 'boreal',
        systemId: 'pale-ring',
        name: 'Boreal',
        shortName: 'BOREAL',
        kind: 'planet',
        position: [-182000, -30000, 156000],
        radius: 11800,
        dockRadius: 17000,
        faction: 'frontier-miners',
        accent: '#a6cdd6',
        secondary: '#314b5b',
        description: 'An ice-covered moon with deep fractures, dark excavations, and settlements built around long supply lines.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 0.48,
            food: 1.44,
            medicine: 1.34,
            electronics: 1.22,
            machinery: 1.3,
            ore: 0.74,
            gold: 0.82,
            scrap: 0.76,
            luxuries: 1.62,
            arms: 1.18,
        },
        marketBias: {
            water: 46,
            food: -24,
            medicine: -20,
            electronics: -12,
            machinery: -18,
            ore: 22,
            gold: 5,
            scrap: 18,
            luxuries: -34,
            arms: 14,
        },
        shipsForSale: ['prospector', 'atlas'],
        encounterRate: 0.4,
        people: [
            {
                id: 'soren-vek',
                name: 'Soren Vek',
                role: 'Extraction supervisor',
                marketTipster: true,
                affiliation: 'Frontier Miners Cooperative',
                portraitSeed: 434,
                lines: [
                    'Water is plentiful on Boreal. Getting it into a pressure tank is the part that costs money.',
                    'A mine can wait. A settlement with an empty food locker cannot.',
                    'Ore leaves the moon cheaply; machinery comes back expensive and usually late.',
                ],
            },
            {
                id: 'aya-north',
                name: 'Aya North',
                role: 'Colony medic',
                affiliation: 'Civilian Medical Service',
                portraitSeed: 447,
                lines: [
                    'Cold keeps a lot of things stable. It also makes every mistake harder to undo.',
                    'If you have room for medicine, take it. Someone at the next settlement is already counting on you.',
                    'Nacre needs samples and Boreal needs parts. The route between them is never as empty as it looks.',
                ],
            },
            {
                id: 'halden-ree',
                name: 'Halden Ree',
                role: 'Ice-hauler captain',
                affiliation: 'Free Merchants Compact',
                portraitSeed: 460,
                lines: [
                    'The rings make distance hard to judge. Use your instruments, then give yourself more room.',
                    'A full water hold is honest work, but it makes your ship interesting to the wrong people.',
                    'Boreal crews do not need promises. We need a delivery time and a pilot who keeps it.',
                ],
            },
        ],
    },

    shepherd: {
        id: 'shepherd',
        systemId: 'pale-ring',
        name: 'Shepherd Relay',
        shortName: 'SHEPHERD',
        kind: 'station',
        position: [-52000, 10000, 178000],
        radius: 680,
        dockRadius: 1100,
        faction: 'concord',
        accent: '#b7d4d7',
        secondary: '#3f5c68',
        description: 'A tiny navigation relay in a clear gap in the rings, important because it is the last quiet stop before the dense bands.',
        services: {
            fuel: true,
            repair: true,
            market: false,
            bar: false,
            shipyard: false,
            outfitting: false,
            missions: true,
            race: false,
        },
        encounterRate: 0.38,
    },

    'pale-rings': {
        id: 'pale-rings',
        systemId: 'pale-ring',
        name: 'The Pale Rings',
        shortName: 'PALE RINGS',
        kind: 'rings',
        position: [120000, 0, 92000],
        radius: 3650,
        faction: 'frontier-miners',
        accent: '#c0d5d4',
        secondary: '#445964',
        description: 'A vast field of ice, dust, and rock with shifting corridors, lost probes, hidden caches, and unreliable sensors.',
        encounterRate: 0.58,
    },
};
