// New-system content kept separate from the legacy location table while the
// galaxy model is rolled out.  The catalog is deliberately data-only: callers
// can merge or filter it without having to import any game systems.

export const GALAXY_LOCATIONS = {
    cairn: {
        id: 'cairn',
        systemId: 'helios-verge',
        name: 'Cairn Yard',
        shortName: 'CAIRN',
        kind: 'station',
        position: [-158000, 22000, 146000],
        radius: 520,
        dockRadius: 980,
        faction: 'salvage-union',
        guilds: ['salvage'],
        accent: '#c98a52',
        secondary: '#3d2e2b',
        description: 'A small fuel and repair depot beside the Mourning Line, and the home of Helios Verge’s informal racing scene.',
        services: {
            fuel: true,
            repair: true,
            market: false,
            bar: true,
            shipyard: false,
            outfitting: false,
            missions: false,
            race: true,
        },
        encounterRate: 0.48,
        people: [
            {
                id: 'juno-rell',
                name: 'Juno Rell',
                role: 'Race coordinator',
                affiliation: 'Cairn Yard Racing League',
                portraitSeed: 214,
                lines: [
                    'You made it to Cairn. Are you here to race, or are you here to watch someone else hit a wreck?',
                    'The next gate is not the finish; hold your line and save afterburner for the exit.',
                    'The Mourning Run is drawing faster hulls this cycle, and the inner shortcut is still open.',
                ],
            },
            {
                id: 'merrit-voss',
                name: 'Merrit Voss',
                role: 'Depot mechanic',
                affiliation: 'Salvage Union',
                portraitSeed: 227,
                lines: [
                    'Merrit Voss. Park the ship where I can reach it, then tell me what the wrecks did to you.',
                    'Keep your approach slow near the hull plates; a salvage beam cannot repair a collision.',
                    'A new claim beacon lit inside the Mourning Line, but two crews are already disputing it.',
                ],
            },
        ],
    },

    'meridian-prime': {
        id: 'meridian-prime',
        systemId: 'meridian',
        name: 'Meridian Prime',
        shortName: 'MERIDIAN',
        kind: 'planet',
        position: [198000, -32000, -174000],
        radius: 18400,
        dockRadius: 23800,
        faction: 'concord',
        guilds: ['merchant', 'bounty'],
        accent: '#7ebbd8',
        secondary: '#233a53',
        description: 'A crowded core world wrapped in orbital infrastructure, consuming raw materials and exporting manufactured goods.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 1.08,
            food: 1.04,
            medicine: 0.88,
            electronics: 0.76,
            machinery: 0.84,
            ore: 0.72,
            gold: 0.92,
            scrap: 0.82,
            luxuries: 0.94,
            arms: 1.22,
        },
        marketBias: {
            water: 8,
            food: 10,
            medicine: -12,
            electronics: -20,
            machinery: -18,
            ore: 25,
            gold: 4,
            scrap: 18,
            luxuries: -6,
            arms: 16,
        },
        shipsForSale: ['talon', 'atlas', 'lancer'],
        encounterRate: 0.22,
        people: [
            {
                id: 'leon-vale',
                name: 'Leon Vale',
                role: 'Orbital market factor',
                marketTipster: true,
                affiliation: 'Merchant Guild',
                portraitSeed: 241,
                lines: [
                    'Welcome to Meridian Prime. Give me your origin and destination, and I’ll show you the useful prices.',
                    'Do not fill the hold before checking the return leg; Meridian’s cheap electronics leave little room for a second cargo.',
                    'Customs tightened inspections on cargo from Redwake after another unregistered shipment came through.',
                ],
            },
            {
                id: 'sela-orrin',
                name: 'Sela Orrin',
                role: 'Concord customs liaison',
                affiliation: 'Concord Patrol',
                portraitSeed: 253,
                lines: [
                    'Sela Orrin, Concord customs. If your manifest is ready, we can keep this conversation short.',
                    'Keep your transponder live in the approach lane and make sure the cargo count matches the sealed hold.',
                    'The gate records show more dark arrivals from Redwake this week, so patrols are checking closer to Meridian Prime.',
                ],
            },
            {
                id: 'tomas-quin',
                name: 'Tomas Quin',
                role: 'Dockside courier',
                affiliation: 'Free Merchants Compact',
                portraitSeed: 266,
                lines: [
                    'Tomas Quin, courier desk. I can find a fast contract, but I cannot make a late pilot look punctual.',
                    'Set your course before you launch and leave enough fuel for the final approach.',
                    'Argent is clearing a backlog of hulls, and its outbound cargo queues are stretching into the Foundry Lanes.',
                ],
            },
        ],
    },

    argent: {
        id: 'argent',
        systemId: 'meridian',
        name: 'Argent Shipworks',
        shortName: 'ARGENT',
        kind: 'station',
        position: [-122000, 30000, 144000],
        radius: 1420,
        dockRadius: 2080,
        faction: 'concord',
        guilds: ['merchant'],
        accent: '#a7c8d2',
        secondary: '#30424d',
        description: 'A vast orbital construction complex where civilian and military hulls are assembled, repaired, and refitted.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 1.02,
            food: 1.02,
            medicine: 0.96,
            electronics: 0.72,
            machinery: 0.68,
            ore: 0.78,
            gold: 0.88,
            scrap: 0.65,
            luxuries: 1.12,
            arms: 0.9,
        },
        marketBias: {
            water: 2,
            food: 3,
            medicine: -4,
            electronics: -26,
            machinery: -30,
            ore: 20,
            gold: 5,
            scrap: 28,
            luxuries: -10,
            arms: 10,
        },
        shipsForSale: ['vanguard', 'lancer', 'atlas'],
        encounterRate: 0.26,
        people: [
            {
                id: 'arden-kai',
                name: 'Arden Kai',
                role: 'Shipwright foreman',
                affiliation: 'Argent Shipworks',
                portraitSeed: 279,
                lines: [
                    'Arden Kai, Argent foreman. Tell me what the ship must do, and I’ll tell you which hull can do it.',
                    'Compare the launcher and magazine space before you buy; a bigger hull does not automatically carry more ordnance.',
                    'The Foundry Lanes are busy with new frigates, and test flights are getting priority over civilian traffic.',
                ],
            },
            {
                id: 'mira-kest',
                name: 'Mira Kest',
                role: 'Outfitting broker',
                marketTipster: true,
                affiliation: 'Merchant Guild',
                portraitSeed: 291,
                lines: [
                    'Mira Kest. Bring your current fitting and your budget; we can work from there.',
                    'Fit the launcher for the ammunition you can actually replace, then leave room for the mission cargo.',
                    'Meridian Prime is buying finished machinery again, while frontier yards are taking Argent’s scrap.',
                ],
            },
            {
                id: 'bram-tel',
                name: 'Bram Tel',
                role: 'Test-flight pilot',
                affiliation: 'Concord Patrol',
                portraitSeed: 304,
                lines: [
                    'Bram Tel, test flight. If the warning lights change when you turn, I want to hear about it.',
                    'Test a new loadout with a full hold; mass changes the turn and the braking distance.',
                    'Concord is reserving a clear lane through the Foundry Lanes for the next round of trials.',
                ],
            },
        ],
    },

    'gatehouse-twelve': {
        id: 'gatehouse-twelve',
        systemId: 'meridian',
        name: 'Gatehouse Twelve',
        shortName: 'GATEHOUSE',
        kind: 'station',
        position: [-198000, 16000, 188000],
        radius: 760,
        dockRadius: 1250,
        faction: 'concord',
        guilds: [],
        accent: '#729eb8',
        secondary: '#293b4a',
        description: 'A compact Concord checkpoint on one of Meridian’s primary jump approaches.',
        services: {
            fuel: true,
            repair: true,
            market: false,
            bar: false,
            shipyard: false,
            outfitting: false,
            missions: true,
            race: false,
        },
        encounterRate: 0.18,
    },

    'foundry-lanes': {
        id: 'foundry-lanes',
        systemId: 'meridian',
        name: 'The Foundry Lanes',
        shortName: 'FOUNDRY',
        kind: 'field',
        position: [-94000, 18000, 137000],
        radius: 3200,
        faction: 'concord',
        accent: '#8daeb5',
        secondary: '#303c46',
        description: 'The crowded industrial space around Argent, where freighters, construction craft, and patrols cross constantly.',
        encounterRate: 0.42,
    },

    blackglass: {
        id: 'blackglass',
        systemId: 'redwake',
        name: 'Blackglass',
        shortName: 'BLACKGLASS',
        kind: 'station',
        position: [-178000, -26000, 142000],
        radius: 5480,
        dockRadius: 7920,
        faction: 'red-talons',
        guilds: ['syndicate', 'merchant'],
        accent: '#d26759',
        secondary: '#4c2025',
        description: 'A sprawling freeport cut into a dark moon, held together by uneasy bargains between crews, merchants, and syndicates.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 1.62,
            food: 1.48,
            medicine: 1.58,
            electronics: 1.08,
            machinery: 1.25,
            ore: 0.95,
            gold: 0.76,
            scrap: 0.72,
            luxuries: 0.86,
            arms: 0.74,
        },
        marketBias: {
            water: -30,
            food: -26,
            medicine: -28,
            electronics: 4,
            machinery: -8,
            ore: 14,
            gold: 12,
            scrap: 24,
            luxuries: 16,
            arms: 48,
        },
        shipsForSale: ['talon', 'vanguard', 'prospector'],
        encounterRate: 0.62,
        people: [
            {
                id: 'vesh-orr',
                name: 'Vesh Orr',
                role: 'Freeport fixer',
                marketTipster: true,
                affiliation: 'Red Talon Syndicate',
                portraitSeed: 318,
                lines: [
                    'Vesh Orr. You found Blackglass, so you probably already know that discretion costs extra.',
                    'If you run dark, cut your emissions before the patrol gets close; a silent transponder is not a silent ship.',
                    'The Talons are paying well for electronics, and that has made the route from Cinder much less quiet.',
                ],
            },
            {
                id: 'nara-quill',
                name: 'Nara Quill',
                role: 'Independent broker',
                marketTipster: true,
                affiliation: 'Free Merchants Compact',
                portraitSeed: 331,
                lines: [
                    'Nara Quill, independent broker. Tell me whether you want a clean price or a quiet delivery.',
                    'Count the escort and the den fee before you call a Redwake quote profitable.',
                    'Cinder’s refinery is running again, and Blackglass is short on the machinery it needs to keep up.',
                ],
            },
            {
                id: 'kellan-rusk',
                name: 'Kellan Rusk',
                role: 'Mercenary captain',
                affiliation: 'Independent',
                portraitSeed: 344,
                lines: [
                    'Kellan Rusk. If you’re taking a belt contract, I’ll tell you where the rocks stop protecting you.',
                    'Use the debris for cover, but keep an escape vector; pirates wait for pilots who fly into dead ends.',
                    'Ash Crown has been hitting refinery haulers in the Redwake Belt and selling their transponder keys.',
                ],
            },
        ],
    },

    cinder: {
        id: 'cinder',
        systemId: 'redwake',
        name: 'Cinder Station',
        shortName: 'CINDER',
        kind: 'station',
        position: [188000, 14000, -160000],
        radius: 1260,
        dockRadius: 1860,
        faction: 'free-merchants',
        guilds: ['merchant'],
        accent: '#c48a62',
        secondary: '#473338',
        description: 'An aging independent industrial station kept alive by refining, freight work, and stubborn local crews.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 1.38,
            food: 1.25,
            medicine: 1.3,
            electronics: 1.18,
            machinery: 0.8,
            ore: 0.64,
            gold: 0.86,
            scrap: 0.7,
            luxuries: 1.42,
            arms: 1.02,
        },
        marketBias: {
            water: -18,
            food: -12,
            medicine: -16,
            electronics: 10,
            machinery: -22,
            ore: 36,
            gold: 7,
            scrap: 30,
            luxuries: -20,
            arms: 18,
        },
        shipsForSale: ['prospector', 'atlas'],
        encounterRate: 0.5,
        people: [
            {
                id: 'mara-jen',
                name: 'Mara Jen',
                role: 'Station quartermaster',
                marketTipster: true,
                affiliation: 'Free Merchants Compact',
                portraitSeed: 357,
                lines: [
                    'Mara Jen, Cinder quartermaster. Tell me what the station needs and how much room you have left.',
                    'Keep a reserve of water and machinery mass; a refinery run is no use if you cannot make the return.',
                    'Blackglass is asking for medigel again, while Torchwell has fuel but almost no spare parts.',
                ],
            },
            {
                id: 'dax-hollis',
                name: 'Dax Hollis',
                role: 'Refinery engineer',
                affiliation: 'Cinder Independent Assembly',
                portraitSeed: 369,
                lines: [
                    'Dax Hollis. The refinery is loud because it is working; if it goes quiet, call me immediately.',
                    'Do not run the drive hot all the way to Torchwell; short afterburner bursts leave more margin for docking.',
                    'One of Cinder’s pumps failed yesterday, and the replacement shipment from Argent is late.',
                ],
            },
            {
                id: 'rhea-sol',
                name: 'Rhea Sol',
                role: 'Freight dispatcher',
                affiliation: 'Merchant Guild',
                portraitSeed: 382,
                lines: [
                    'Rhea Sol, freight dispatch. I can put a real deadline on a job, so give me a route you can actually fly.',
                    'Leave time to slow down at the destination; a late approach still misses the contract.',
                    'More pilots are taking Cinder runs to Blackglass, and pirates are waiting closer to the approach.',
                ],
            },
        ],
    },

    torchwell: {
        id: 'torchwell',
        systemId: 'redwake',
        name: 'Torchwell',
        shortName: 'TORCHWELL',
        kind: 'station',
        position: [-48000, -18000, 212000],
        radius: 820,
        dockRadius: 1320,
        faction: 'free-merchants',
        guilds: [],
        accent: '#d18c55',
        secondary: '#492b2b',
        description: 'A lonely outer-route refinery offering fuel, basic repairs, and little else.',
        services: {
            fuel: true,
            repair: true,
            market: false,
            bar: false,
            shipyard: false,
            outfitting: false,
            missions: true,
            race: false,
        },
        encounterRate: 0.56,
    },

    'redwake-belt': {
        id: 'redwake-belt',
        systemId: 'redwake',
        name: 'The Redwake Belt',
        shortName: 'REDWAKE',
        kind: 'field',
        position: [118000, 18000, -62000],
        radius: 3420,
        faction: 'red-talons',
        accent: '#9a6c61',
        secondary: '#39252b',
        description: 'A broken asteroid region where raiders, bounty targets, and patient pilots use the rocks to disappear.',
        encounterRate: 0.78,
    },

    nacre: {
        id: 'nacre',
        systemId: 'pale-ring',
        name: 'Nacre Station',
        shortName: 'NACRE',
        kind: 'station',
        position: [208000, 26000, -176000],
        radius: 1320,
        dockRadius: 1950,
        faction: 'concord',
        guilds: ['mining'],
        accent: '#c4d9dc',
        secondary: '#3b5965',
        description: 'A scientific habitat supporting planetary research, medical laboratories, and long-range survey work.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 0.7,
            food: 1.2,
            medicine: 0.72,
            electronics: 0.78,
            machinery: 1.42,
            ore: 1.16,
            gold: 0.9,
            scrap: 1.34,
            luxuries: 1.48,
            arms: 1.26,
        },
        marketBias: {
            water: 24,
            food: -14,
            medicine: 28,
            electronics: 24,
            machinery: -26,
            ore: -8,
            gold: 4,
            scrap: -16,
            luxuries: -25,
            arms: 8,
        },
        shipsForSale: ['talon', 'prospector'],
        encounterRate: 0.34,
        people: [
            {
                id: 'dr-elin-saye',
                name: 'Dr. Elin Saye',
                role: 'Research director',
                marketTipster: true,
                affiliation: 'Pale Ring Survey Authority',
                portraitSeed: 395,
                lines: [
                    'I’m Dr. Elin Saye. If your sensor logs are intact, the Pale Ring Survey Authority can use them.',
                    'Record the full scan before you leave a ring corridor; a single contact is not enough to map it.',
                    'A probe went silent near the Pale Rings, and Pavel is sending a search crew through Shepherd Relay.',
                ],
            },
            {
                id: 'pavel-orn',
                name: 'Pavel Orn',
                role: 'Survey dispatcher',
                affiliation: 'Pale Ring Survey Authority',
                portraitSeed: 408,
                lines: [
                    'Pavel Orn, survey dispatch. Give me your last known position and I’ll check the ring traffic.',
                    'Use Shepherd Relay as a checkpoint, then approach the dense bands with a clear return vector.',
                    'The safe corridor through the Pale Rings shifted again, and the old beacon is now off the chart.',
                ],
            },
            {
                id: 'tessa-rye',
                name: 'Tessa Rye',
                role: 'Clinic quartermaster',
                affiliation: 'Civilian Medical Service',
                portraitSeed: 421,
                lines: [
                    'Tessa Rye, clinic stores. If you have room for medicine, I can give you a delivery that matters.',
                    'Keep the cold-chain cases sealed; taking hull damage can cost the fragile-load bonus.',
                    'Boreal’s eastern settlement is short on medigel after a fracture opened beneath the pressure domes.',
                ],
            },
        ],
    },

    boreal: {
        id: 'boreal',
        systemId: 'pale-ring',
        name: 'Boreal',
        shortName: 'BOREAL',
        kind: 'planet',
        position: [-182000, -30000, 156000],
        radius: 11800,
        dockRadius: 17000,
        faction: 'frontier-miners',
        guilds: ['mining', 'merchant'],
        accent: '#a6cdd6',
        secondary: '#314b5b',
        description: 'An ice-covered moon with deep fractures, dark excavations, and settlements built around long supply lines.',
        services: {
            fuel: true,
            repair: true,
            market: true,
            bar: true,
            shipyard: true,
            outfitting: true,
            missions: true,
            race: false,
        },
        economy: {
            water: 0.48,
            food: 1.44,
            medicine: 1.34,
            electronics: 1.22,
            machinery: 1.3,
            ore: 0.74,
            gold: 0.82,
            scrap: 0.76,
            luxuries: 1.62,
            arms: 1.18,
        },
        marketBias: {
            water: 46,
            food: -24,
            medicine: -20,
            electronics: -12,
            machinery: -18,
            ore: 22,
            gold: 5,
            scrap: 18,
            luxuries: -34,
            arms: 14,
        },
        shipsForSale: ['prospector', 'atlas'],
        encounterRate: 0.4,
        people: [
            {
                id: 'soren-vek',
                name: 'Soren Vek',
                role: 'Extraction supervisor',
                marketTipster: true,
                affiliation: 'Frontier Miners Cooperative',
                portraitSeed: 434,
                lines: [
                    'Soren Vek, extraction supervisor. If you’re here for a claim, show me the scan and your cargo limit.',
                    'Do not promise more ore than your hold can take; a claim only counts what you cut and bring back.',
                    'Water output is up on Boreal, but machinery deliveries from Nacre are still behind schedule.',
                ],
            },
            {
                id: 'aya-north',
                name: 'Aya North',
                role: 'Colony medic',
                affiliation: 'Civilian Medical Service',
                portraitSeed: 447,
                lines: [
                    'Aya North, colony medic. Are you here with supplies, or are you another pilot asking for directions out?',
                    'Take the medicine first and keep the ship intact; damaged medical cargo helps nobody.',
                    'The clinic is treating more radiation injuries from the eastern fracture, and the next medigel shipment is overdue.',
                ],
            },
            {
                id: 'halden-ree',
                name: 'Halden Ree',
                role: 'Ice-hauler captain',
                affiliation: 'Free Merchants Compact',
                portraitSeed: 460,
                lines: [
                    'Halden Ree, ice-hauler. I can give you the route, but you still have to fly around the ring traffic.',
                    'Watch the distance to drifting ice and leave room to turn when the scanner fills with returns.',
                    'Nacre is asking for fresh samples, while Boreal’s water tanks are finally running full.',
                ],
            },
        ],
    },

    shepherd: {
        id: 'shepherd',
        systemId: 'pale-ring',
        name: 'Shepherd Relay',
        shortName: 'SHEPHERD',
        kind: 'station',
        position: [-52000, 10000, 178000],
        radius: 680,
        dockRadius: 1100,
        faction: 'concord',
        guilds: [],
        accent: '#b7d4d7',
        secondary: '#3f5c68',
        description: 'A tiny navigation relay in a clear gap in the rings, important because it is the last quiet stop before the dense bands.',
        services: {
            fuel: true,
            repair: true,
            market: false,
            bar: false,
            shipyard: false,
            outfitting: false,
            missions: true,
            race: false,
        },
        encounterRate: 0.38,
    },

    'pale-rings': {
        id: 'pale-rings',
        systemId: 'pale-ring',
        name: 'The Pale Rings',
        shortName: 'PALE RINGS',
        kind: 'rings',
        position: [120000, 0, 92000],
        radius: 3650,
        faction: 'frontier-miners',
        accent: '#c0d5d4',
        secondary: '#445964',
        description: 'A vast field of ice, dust, and rock with shifting corridors, lost probes, hidden caches, and unreliable sensors.',
        encounterRate: 0.58,
    },
};
