import {FRIGATE_MOUNTS} from './frigateMounts.js';
// Generated by scripts/bake-turret-clearance.py. Pivots seat Blender bases on local decks.
export const TURRET_LAYOUTS = {
  andromeda: [{size:'S',pedestal:0,hullHalfLength:7.8,position:[0,0.798781012135374,0.1282083912603972],side:1,axis:1,forwardCone:0,label:'REAR DEFENSE'}],
  torsas: [{size:'S',pedestal:0,hullHalfLength:8,position:[0,1.1000499521450506,0.12484796976909741],side:1,axis:1,forwardCone:0,label:'DORSAL DEFENSE'}],
  'concord-frigate': FRIGATE_MOUNTS,
  "talon": [],
  "wayfarer": [
    {
      "size": "S",
      "pedestal": -0.0,
      "hullHalfLength": 6.09,
      "position": [
        0.0,
        0.9863531553758325,
        -0.48000000000000004
      ],
      "side": 1,
      "axis": 1,
      "forwardCone": 10,
      "label": "TOP TURRET"
    }
  ],
  "vanguard": [
    {
      "size": "S",
      "pedestal": -0.0,
      "hullHalfLength": 5.9,
      "position": [
        -0.7221830172797583,
        0.0,
        0.1
      ],
      "side": -1,
      "axis": 0,
      "forwardCone": 10,
      "label": "PORT TURRET"
    },
    {
      "size": "S",
      "pedestal": -0.0,
      "hullHalfLength": 5.9,
      "position": [
        0.725042602558085,
        0.0,
        0.1
      ],
      "side": 1,
      "axis": 0,
      "forwardCone": 10,
      "label": "STARBOARD TURRET"
    }
  ],
  "prospector": [
    {
      "size": "S",
      "pedestal": -0.0,
      "hullHalfLength": 6.7,
      "position": [
        0.0,
        0.734172311088267,
        0.5
      ],
      "side": 1,
      "axis": 1,
      "forwardCone": 0,
      "label": "REAR TOP TURRET"
    }
  ],
  "lancer": [
    {
      "size": "M",
      "pedestal": -0.0,
      "hullHalfLength": 6.45,
      "position": [
        0.0,
        -0.8163100651643268,
        0.2
      ],
      "side": -1,
      "axis": 1,
      "forwardCone": 10,
      "label": "LOWER TURRET"
    }
  ],
  "atlas": [
    {
      "size": "S",
      "pedestal": -0.0,
      "hullHalfLength": 13.4,
      "position": [
        0.0,
        0.7710145328607895,
        0.55
      ],
      "side": 1,
      "axis": 1,
      "forwardCone": 0,
      "label": "REAR TOP TURRET"
    },
    {
      "size": "S",
      "pedestal": 0.572713,
      "hullHalfLength": 13.4,
      "position": [
        0.0,
        -1.1331719128329298,
        -0.55
      ],
      "side": -1,
      "axis": 1,
      "forwardCone": 10,
      "label": "FORWARD LOWER TURRET"
    }
  ]
};
